source 'https://github.com/CocoaPods/Specs.git'
platform :ios,9.0
use_frameworks!

target 'TE' do
	pod 'TZImagePickerController', '1.9.6'
	pod 'EZAudio', '1.1.5'
	pod 'YYKit', '1.0.9'
   	pod 'WCDB.swift'
	pod 'MJRefresh', '3.1.15.1'
	pod 'SwiftProtobuf', '1.0.2'
	pod 'SocketRocket', '0.5.1'
	pod 'Qiniu', '7.2.2'
end
